DIRECTORY:
  dataset: "./DATA/test/images"
  sample_submission_path : './DATA/test/sample_submission.csv'
  
  # train_serial: "./baseline/results/train/20230626_235432"
  batch_size: 32

TRAIN: 
  train_serial: "20230701_162702"


PREDICT:
  seed: 42
  gpu: 0